"""empty message

Revision ID: 728397f65e70
Revises: 80644ef5fa67
Create Date: 2024-08-03 19:58:46.551980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728397f65e70'
down_revision = '80644ef5fa67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.String(length=32), nullable=False))
        batch_op.create_unique_constraint(None, ['userId'])
        batch_op.drop_column('userid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('userId')

    # ### end Alembic commands ###
